{{- range .Values.namespaces }}
  {{- $namespace := .name }}
  {{- range .users }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ . }}-ocpai-cluster-role
rules:
  - verbs:
      - get
    apiGroups:
      - kubeflow.org
    resources:
      - notebooks
    resourceNames:
      - {{ . }}-nb
  {{- end }}
{{- end }}